name: result
version: 0.0.2
description: >-
  Object that represents either a success or a failure
author: LiewLi <liulimg@gmail.com>
homepage: https://github.com/LiewLi/result
environment:
  sdk: '>=2.0.0 <3.0.0'