name: result
version: 1.0.2
description: >-
  Object that represents either a success or a failure; 'success' or 'failure' for each case
author: LiewLi <liulimg@gmail.com>
homepage: https://github.com/LiewLi/result
environment:
  sdk: '>=2.0.0 <3.0.0'